services:
  - type: web
    name: real-rp-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: APPLICATION_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: STAFF_ROLE_ID
        sync: false
      - key: ADMIN_ROLE_ID
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: SUGGESTIONS_CHANNEL_ID
        sync: false
      - key: TICKET_CATEGORY_ID
        sync: false
